# GitHub Sponsors funding file
# Add your funding links here if you want to enable GitHub Sponsors button

# github: [your-github-username]
# patreon: your-username
# open_collective: your-project
# ko_fi: your-username
# custom: ["https://your-website.com/donate", "https://buymeacoffee.com/your-username"]

# Example: Accept crypto donations
custom: ["Polygon (SHIB): 0x26fc06D17Eb82638b25402D411889EEb69F1e7C5"]
